# -*- coding: utf-8 -*-
"""travel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAiTq8eEPeA-FoziUPAWxoSknB-GGY5K
"""

# pip install openai langchain langchain-openai streamlit
import streamlit as st
from langchain.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

# OpenAI API 키 설정(colab)
# from google.colab import userdata
# api_key = userdata.get('opanai_key')
api_key = st.secrets["OPENAI_API_KEY"]

template = """
너는 한국 여행 전문가야.
사용자가 입력한 조건에 맞는 여행지를 3곳 추천해줘.
추천 이유도 간단히 써줘.

입력: {user_input}

---
형식:
1. 여행지명 - 추천 이유
2. 여행지명 - 추천 이유
3. 여행지명 - 추천 이유
"""

prompt = PromptTemplate(template=template, input_variables=["user_input"])
llm = ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo", openai_api_key=api_key)

# ✅ 최신 방식: LLMChain 없이 직접 연결
#chain = LLMChain(llm=llm, prompt=prompt)
chain = prompt | llm

# --- Streamlit UI ---
st.title("🇰🇷 여행지 추천 챗봇")

user_input = st.text_input("여행 조건을 입력해주세요 (예: 서울 근교 자연 여행지, 봄 당일치기 등)")

if st.button("추천받기") and user_input:
    with st.spinner("추천 중입니다..."):
        result = chain.run({"user_input": user_input})
        st.success("추천 완료!")
        st.text_area("추천 결과", result, height=200)

# response = chain.run({"user_input": "서울에서 당일치기 가능한 자연 여행지 추천해줘"})
# print(response)